import type { Metadata } from "next";

import { Inter } from "next/font/google";
import "../styles/globals.css";
import { Amplify } from 'aws-amplify';
import { generateClient } from 'aws-amplify/api';
import config from '../src/amplifyconfiguration.json';
Amplify.configure(config);
const inter = Inter({ subsets: ["latin"] });
const client = generateClient();
export const metadata: Metadata = {
  title: "Inspirational Quote Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        </body>
    </html>
  );
}
